name: Snyk Security

on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Snyk Code (SAST)
        run: snyk code test --severity-threshold=high

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source (SCA)
        run: snyk test --all-projects --severity-threshold=high

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
